name: Cypress Tests - Manual and Daily Schedule

on:
  workflow_dispatch:  # Gatilho manual para rodar o workflow
  schedule:
    - cron: '0 23 * * *'  # Executa diariamente às 23h UTC

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Configuração do Node.js (dependência do Cypress)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Instalar as dependências do projeto
      - name: Install dependencies
        run: npm install  # Instala as dependências Cypress

      # Step 4: Executar os testes do Cypress
      - name: Run Cypress tests
        run: npm run test  # Substitua pelo comando de execução de seus testes

      # Step 5: Upload de vídeos em caso de falha nos testes
      - name: Upload Cypress videos and screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v3  # Atualizado para v3
        with:
          name: cypress-videos
          path: cypress/videos

      # Step 6: Upload de screenshots em caso de falha nos testes
      - name: Upload Cypress screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v3  # Atualizado para v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots
